# Generated by Django 5.0.1 on 2025-02-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('rules_and_regulations', models.TextField()),
                ('venue', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='event_registration/images')),
            ],
        ),
    ]
