# Generated by Django 5.0.1 on 2025-02-07 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration', '0006_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events', to='event_registration.participant'),
        ),
        migrations.AddField(
            model_name='participant',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='coupon_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizers', to='event_registration.event'),
        ),
    ]
