# Generated by Django 5.0.1 on 2025-02-07 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration', '0007_event_participants_participant_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='teammate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammates', to='event_registration.event')),
                ('team_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammates', to='event_registration.participant')),
            ],
        ),
    ]
